import json, re

RUTA = r"C:\Users\Usuario\Desktop\saca-el-carnet\saca_el_carnet\assets\preguntas_C.json"

nuevas = [
    # ── drivenyou test 1 ────────────────────────────────────────────────────
    {"enunciado": "Si el manómetro marca poca presión, ¿cómo estará el aceite?", "opciones": ["Muy caliente.", "Frío.", "Templado."], "respuesta_correcta": 0, "explicacion": "Una baja presión en el manómetro indica que el aceite está muy caliente y ha perdido viscosidad, reduciendo así la presión que ejerce sobre el sistema."},
    {"enunciado": "Si realiza el doble embrague en su camión que dispone de caja de cambios sincronizada, ¿tendrá influencia en el consumo?", "opciones": ["No, no tiene nada que ver.", "Aumentando el consumo porque el camión pierde inercia al alargarse el proceso de cambio de marcha.", "No influye, sin embargo, al disminuir la relación de marcha, aumenta la potencia del motor pero no su consumo."], "respuesta_correcta": 1, "explicacion": "El doble embrague en cajas sincronizadas alarga el proceso de cambio de marcha, haciendo que el camión pierda inercia y aumentando el consumo de combustible."},
    {"enunciado": "Si encuentra agua en el aceite del motor, ¿a qué puede ser debido?", "opciones": ["A la rotura o deterioro de algún manguito.", "A una ranura en el cárter.", "A que la junta de culata está quemada o en mal estado."], "respuesta_correcta": 2, "explicacion": "La junta de culata dañada permite que el líquido refrigerante se mezcle con el aceite del motor, lo que se detecta como agua o emulsión en el aceite."},
    {"enunciado": "Si la separación entre los centros de los dos ejes que componen el eje doble del camión es de 1,25 metros, ¿cuál es la masa máxima autorizada sobre dicho eje doble?", "opciones": ["16 toneladas.", "11,5 toneladas.", "18 toneladas."], "respuesta_correcta": 0, "explicacion": "Cuando la separación entre ejes dobles es de 1,25 metros, la normativa establece que la MMA sobre ese eje doble no puede exceder las 16 toneladas."},
    {"enunciado": "¿Cómo se denomina la masa del vehículo con su equipo fijo autorizado, dotación completa de agua, combustible, lubricante, repuestos, herramientas y accesorios, pero sin personal, pasajeros ni carga?", "opciones": ["Masa máxima autorizada.", "Tara.", "Masa en carga."], "respuesta_correcta": 1, "explicacion": "La tara es el peso del vehículo equipado y listo para circular, sin carga útil ni pasajeros; es el peso 'en vacío' del camión."},
    {"enunciado": "Si está obligado a utilizar el tacógrafo y durante una semana ha conducido 50 horas, ¿cuántas horas puede conducir como máximo la semana siguiente?", "opciones": ["40 horas.", "50 horas.", "56 horas."], "respuesta_correcta": 2, "explicacion": "El máximo bisemanal es 90 horas. Si la primera semana se conducen 50, la siguiente se pueden conducir hasta 56 horas (el máximo semanal permitido)."},
    {"enunciado": "Si desea transportar en la caja de un camión una carga indivisible de 4 metros de altura, ¿necesita autorización especial?", "opciones": ["Sí, en todo caso.", "Sólo cuando se deba circular por obras de paso.", "No, porque no rebasa las dimensiones máximas permitidas."], "respuesta_correcta": 2, "explicacion": "La altura máxima permitida en España es de 4 metros. Una carga de exactamente 4 metros no supera ese límite y no requiere autorización especial."},
    {"enunciado": "¿Le está permitido estacionar en doble fila el camión para efectuar operaciones de carga y descarga?", "opciones": ["Sí, excepto en autovías y autopistas.", "No, en ningún caso.", "Sí, pero solamente en vías dentro de poblado."], "respuesta_correcta": 1, "explicacion": "El estacionamiento en doble fila está prohibido en cualquier vía y circunstancia para los camiones, al constituir un obstáculo grave para la circulación."},
    {"enunciado": "Se denomina transporte público por carretera...", "opciones": ["Al transporte gratuito.", "Al que realizan el estado y los ayuntamientos.", "Al que se realiza por cuenta ajena, mediante retribución económica."], "respuesta_correcta": 2, "explicacion": "El transporte público por carretera es aquel que se presta a terceros a cambio de una contraprestación económica, con independencia de quien lo realice."},
    {"enunciado": "¿Está permitido que su camión lleve un dispositivo GPS?", "opciones": ["Sí, porque es compatible con la obligatoria atención permanente a la conducción.", "No, ya que en ningún caso es compatible con la obligatoria atención permanente a la conducción.", "Sí, pero no está recomendado su uso."], "respuesta_correcta": 0, "explicacion": "El GPS es compatible con la atención permanente a la conducción, siempre que el conductor no lo manipule mientras conduce."},
    {"enunciado": "¿En qué tipo de vías suele registrarse mayor número de víctimas mortales?", "opciones": ["En vías interurbanas.", "En autopistas y autovías.", "En vías urbanas y travesías."], "respuesta_correcta": 0, "explicacion": "Las vías interurbanas convencionales concentran el mayor número de víctimas mortales por sus altas velocidades, la falta de separación de sentidos y la ausencia de sistemas de contención."},
    {"enunciado": "¿Se debe revisar el nivel de líquido del sistema de dirección del camión?", "opciones": ["Sólo se revisará si se observa un aumento anormal del esfuerzo para girar el volante.", "Sí, y comprobar que el nivel se encuentra entre las marcas de máximo y mínimo.", "Sí, y comprobar que el depósito esté rebosando."], "respuesta_correcta": 1, "explicacion": "El nivel del líquido de la dirección asistida debe mantenerse entre las marcas de mínimo y máximo; por encima o por debajo puede dañar el sistema."},
    {"enunciado": "El consumo del motor se incrementa si los neumáticos...", "opciones": ["Se inflan con aire caliente.", "Tienen la presión indicada por el fabricante.", "Tienen una presión menor que la recomendada."], "respuesta_correcta": 2, "explicacion": "Una presión de neumático inferior a la recomendada aumenta la superficie de contacto y la resistencia a la rodadura, lo que eleva el consumo de combustible."},
    {"enunciado": "Con un camión, ¿está permitido adelantar a un ciclista si para dejar 1,5 metros de distancia lateral es necesario ocupar el carril contiguo por el que circula un vehículo en sentido contrario?", "opciones": ["No; se debe esperar a que el adelantamiento se pueda realizar con seguridad.", "Sí; se ocupará el carril de sentido contrario aunque exista riesgo de colisión.", "Sí, se puede reducir la distancia lateral a 1 metro si el ciclista circula por el arcén."], "respuesta_correcta": 0, "explicacion": "La seguridad es prioritaria. Si no se puede mantener la distancia lateral de 1,5 metros sin invadir el carril contrario con riesgo de colisión, hay que esperar."},
    {"enunciado": "Al arrancar en frío el motor del camión tras un período parado, ¿qué se debe hacer para que los calderines neumáticos de freno alcancen la presión adecuada?", "opciones": ["Esperar entre 30 y 60 segundos antes de iniciar la marcha.", "Iniciar la marcha inmediatamente y realizar saltos de marcha.", "Dar acelerones cortos y rápidos sin pasar de las 2.000 rpm."], "respuesta_correcta": 0, "explicacion": "Los sistemas de frenos neumáticos necesitan tiempo para acumular la presión mínima de funcionamiento. Se deben esperar entre 30 y 60 segundos antes de iniciar la marcha."},
    {"enunciado": "En caso de sufrir o presenciar un accidente de tráfico, ¿qué es conveniente saber sobre el teléfono de emergencias 112?", "opciones": ["Que funciona en España y Portugal, pero no en el resto de los países de la Unión Europea.", "Que coordina los profesionales de la Sanidad, pero no a las Fuerzas de la Policía ni a los Bomberos.", "Que es posible el establecimiento de llamada en una zona sin cobertura y con el móvil bloqueado."], "respuesta_correcta": 2, "explicacion": "El 112 puede establecer llamada incluso sin cobertura de la propia red y con el móvil bloqueado, y coordina todos los servicios de emergencia en toda la UE."},
    {"enunciado": "El conductor de un vehículo pesado advierte que pretende adelantarle un turismo y no hay situación de riesgo. ¿Qué debe hacer?", "opciones": ["Facilitar la maniobra o impedirla, dependiendo del tipo de vía por el que circula.", "Reducir la velocidad, o incluso detenerse, para facilitar el adelantamiento.", "Si es posible, ceñirse a la derecha de la calzada; si no lo es, poner el intermitente derecho."], "respuesta_correcta": 2, "explicacion": "El conductor del vehículo pesado debe facilitar el adelantamiento ciñéndose a la derecha o, si no es posible, indicarlo con el intermitente derecho."},

    # ── drivenyou test 2 ────────────────────────────────────────────────────
    {"enunciado": "En una inspección técnica en carretera, ¿cómo se denominan las deficiencias detectadas que suponen un riesgo inmediato y directo para la seguridad vial?", "opciones": ["Deficiencias peligrosas.", "Deficiencias muy graves.", "Deficiencias graves."], "respuesta_correcta": 1, "explicacion": "Las deficiencias que suponen un riesgo inmediato para la seguridad vial se clasifican como 'muy graves' y pueden motivar la inmovilización inmediata del vehículo."},
    {"enunciado": "¿Qué caracteriza a las lámparas de xenón?", "opciones": ["Funcionan a temperaturas más bajas que las lámparas de filamento.", "Funcionan a una tensión de unos 20.000 voltios.", "Están compuestas por miles de pequeños diodos, por lo que son más duraderas."], "respuesta_correcta": 1, "explicacion": "Las lámparas de xenón requieren una tensión de arranque de aproximadamente 20.000 voltios para ionizar el gas xenón y producir luz."},
    {"enunciado": "Circula por una calzada de 6 metros de ancho en condiciones meteorológicas especialmente desfavorables. ¿Qué alumbrado deberá utilizar?", "opciones": ["La luz de carretera junto con las antinieblas delanteras y traseras obligatoriamente.", "La luz de carretera junto con las antinieblas delanteras y traseras opcionalmente.", "La luz de cruce junto con antiniebla trasera y, opcionalmente, la antiniebla delantera."], "respuesta_correcta": 2, "explicacion": "En condiciones adversas de visibilidad se usa la luz de cruce; la antiniebla trasera es obligatoria y la delantera es opcional."},
    {"enunciado": "¿Cuánto puede sobresalir la carga divisible en un vehículo de transporte de mercancías cuya longitud es superior a 5 metros?", "opciones": ["Nada.", "2 metros por la parte delantera y 3 metros por la trasera.", "Un tercio de la longitud del vehículo."], "respuesta_correcta": 1, "explicacion": "Para vehículos de más de 5 metros de longitud, la carga divisible puede sobresalir hasta 2 metros por la parte delantera y 3 metros por la trasera."},
    {"enunciado": "¿Dónde se colocará el distintivo de vehículos de transporte de mercancías (señal V-23) que mejora la visibilidad de los vehículos largos y pesados?", "opciones": ["En la parte delantera y trasera del vehículo, así como en su lateral.", "En la parte trasera del vehículo, así como en su lateral.", "En la parte delantera y trasera del vehículo."], "respuesta_correcta": 1, "explicacion": "La señal V-23 mejora la visibilidad lateral y trasera; por eso se coloca en la parte trasera y en los laterales del vehículo."},
    {"enunciado": "Al cambiar de marcha en una pendiente ascendente, el vehículo pierde potencia. ¿Qué consecuencia tiene esta pérdida?", "opciones": ["Un aumento de la velocidad.", "Una reducción de la velocidad.", "Un descenso de la temperatura del motor."], "respuesta_correcta": 1, "explicacion": "En pendiente ascendente, la interrupción de la tracción durante el cambio de marcha hace que la gravedad frene el vehículo, reduciendo su velocidad."},
    {"enunciado": "¿Qué puede favorecer la aparición de la somnolencia al volante?", "opciones": ["Mantener la temperatura del habitáculo entre los 20 y 23 °C.", "Mantener el vehículo bien ventilado.", "Una comida abundante, copiosa o rica en grasas."], "respuesta_correcta": 2, "explicacion": "Las comidas copiosas o ricas en grasas provocan somnolencia por el esfuerzo digestivo, representando un riesgo grave durante la conducción."},
    {"enunciado": "Un camión y un conjunto de vehículos llegan a la vez a un paso estrecho que no permite el paso simultáneo. A falta de señalización, ¿quién debe dar marcha atrás?", "opciones": ["El conductor del camión.", "El conductor del conjunto de vehículos.", "El conductor que tenga que recorrer menor distancia con su vehículo."], "respuesta_correcta": 2, "explicacion": "A falta de señalización específica, debe ceder el paso el conductor que tenga que recorrer menor distancia para despejar el paso, minimizando la interrupción del tráfico."},
    {"enunciado": "¿Qué indica el índice de carga de un neumático?", "opciones": ["La máxima presión a la que puede ser inflado.", "El peso máximo que puede soportar el neumático.", "La velocidad máxima que puede alcanzar."], "respuesta_correcta": 1, "explicacion": "El índice de carga es un código numérico que indica la carga máxima que puede soportar el neumático en condiciones de uso normales."},
    {"enunciado": "La carga debe colocarse en la caja del camión...", "opciones": ["Empezando desde más cerca a más lejos de los ejes, sin dejar huecos.", "Empezando desde más lejos a más cerca de los ejes, sin dejar huecos.", "Colocando los objetos menos pesados primero."], "respuesta_correcta": 0, "explicacion": "Cargar de más cerca a más lejos de los ejes distribuye correctamente el peso y reduce el riesgo de vuelco al mantener bajo el centro de gravedad."},
    {"enunciado": "Conduce un camión. ¿Le está permitido reducir en alguna circunstancia la distancia de seguridad indicada en la señal?", "opciones": ["Sí, para adelantar.", "No, en ningún caso.", "Solamente en caso de congestión."], "respuesta_correcta": 1, "explicacion": "La distancia de seguridad marcada por la señal es un mínimo obligatorio y no puede reducirse bajo ninguna circunstancia."},
    {"enunciado": "Todos los camiones de más de 3.500 kg de MMA están obligados a llevar...", "opciones": ["Dos extintores.", "Un extintor, independientemente de la MMA.", "Un extintor; y los de más de 20 toneladas de MMA deberán llevar dos extintores."], "respuesta_correcta": 2, "explicacion": "La normativa exige un extintor a partir de 3.500 kg de MMA y dos extintores cuando la MMA supera las 20 toneladas."},
    {"enunciado": "Si circula con su camión por una carretera recta y observa que tiende a desviarse hacia uno de los lados, ¿qué debe revisar?", "opciones": ["El paralelismo de las ruedas traseras entre sí.", "El mecanismo que, situado dentro del grupo cónico, reparte el esfuerzo de giro del motor.", "La cota del paralelo del sistema de dirección."], "respuesta_correcta": 0, "explicacion": "Una desviación lateral en recta suele indicar que las ruedas traseras no están alineadas (paralelismo incorrecto), lo que hace tirar el vehículo hacia un lado."},
    {"enunciado": "Algunos accidentes de camiones se deben a...", "opciones": ["Una incorrecta sujeción o distribución de la carga que se transporta.", "Que el centro de gravedad del camión está situado muy bajo.", "Que el centro de gravedad del camión está situado en su eje longitudinal."], "respuesta_correcta": 0, "explicacion": "Una carga mal distribuida o insuficientemente sujeta puede desplazarse durante el trayecto, alterando el equilibrio del vehículo y provocando accidentes."},
    {"enunciado": "En un estrechamiento sin señalizar se encuentran un camión y un tractor. ¿Quién tiene preferencia?", "opciones": ["El camión.", "El tractor.", "El que haya entrado el primero."], "respuesta_correcta": 2, "explicacion": "En un estrechamiento sin señalización específica, tiene preferencia el vehículo que haya entrado primero en el paso estrecho."},
    {"enunciado": "La carga debe colocarse en la caja del camión, empezando desde más cerca a más lejos de los ejes y sin dejar huecos, para...", "opciones": ["Reducir el riesgo de vuelco.", "Aumentar la carga sobre la quinta rueda.", "Subir el centro de gravedad del camión."], "respuesta_correcta": 0, "explicacion": "Colocar la carga cerca de los ejes y sin huecos mantiene bajo el centro de gravedad del vehículo, lo que reduce el riesgo de vuelco en curvas o frenadas."},
    {"enunciado": "La descarga de datos de las tarjetas de los conductores deberá hacerse, entre otros casos...", "opciones": ["Al menos cada 24 horas para garantizar que no hay sobreescritura.", "Al menos cada 15 días para garantizar que no hay sobreescritura.", "Al menos cada 31 días para garantizar que no hay sobreescritura."], "respuesta_correcta": 2, "explicacion": "La normativa europea exige descargar los datos de la tarjeta del conductor al menos cada 28 días (en la práctica se recomienda como máximo cada 31 días) para evitar la sobreescritura."},
    {"enunciado": "¿Qué elemento extrae el carburante del depósito en un motor diésel?", "opciones": ["La bomba de alimentación.", "La bomba de inyección.", "El pistón, por succión."], "respuesta_correcta": 0, "explicacion": "En un motor diésel, la bomba de alimentación es la encargada de trasladar el gasoil desde el depósito hasta la bomba de inyección."},

    # ── drivenyou test 3 (solo preguntas sin imagen) ────────────────────────
    {"enunciado": "Referente al tacógrafo, si no se compromete la seguridad en carretera y para llegar a un punto de parada adecuado, ¿podrá no cumplir el tiempo máximo de conducción establecido en la norma?", "opciones": ["No, se observarán estrictamente los tiempos, sobre todo en operaciones de tráfico internacional.", "Sí, en la medida necesaria para garantizar la seguridad de las personas, del vehículo o de su carga.", "Solo en territorio nacional, y tendrá que registrar el motivo al llegar a su destino final."], "respuesta_correcta": 1, "explicacion": "La normativa permite exceder el tiempo de conducción en la medida estrictamente necesaria para llegar a un punto de parada seguro, siempre que no se comprometa la seguridad vial."},
    {"enunciado": "Considerando que un conductor obligado al uso del tacógrafo puede realizar una conducción bisemanal de 90 horas, si durante una semana conduce 30 horas, ¿cuántas horas podrá conducir la semana siguiente?", "opciones": ["60 horas.", "56 horas.", "50 horas como máximo."], "respuesta_correcta": 1, "explicacion": "El máximo bisemanal es 90 horas, pero el máximo semanal es 56 horas. Si la primera semana se conducen 30 horas, la segunda podría ser 60 horas en teoría, pero el tope semanal de 56 horas limita a 56 horas como máximo."},

    # ── practicatest test 4 ─────────────────────────────────────────────────
    {"enunciado": "La luz de posición lateral, ¿para qué camiones será obligatoria?", "opciones": ["Para todos los que superen los 6 metros de longitud.", "Para ninguno, ya que son opcionales.", "Para todos los que tengan más de 2,10 metros de ancho."], "respuesta_correcta": 0, "explicacion": "La luz de posición lateral es obligatoria en camiones que superen los 6 metros de longitud, para hacerlos visibles lateralmente a otros usuarios."},
    {"enunciado": "¿Qué deberé hacer para conducir de manera eficiente?", "opciones": ["Adecuar las revoluciones del motor para que al cambiar de marcha éstas queden en la zona roja.", "Adecuar las revoluciones del motor para que al cambiar de marcha éstas queden al principio de la zona verde.", "Adecuar las revoluciones del motor para que al cambiar de marcha éstas queden al final de la zona verde."], "respuesta_correcta": 1, "explicacion": "Para conducir eficientemente se debe cambiar de marcha de modo que las rpm queden al principio de la zona verde, evitando excesos de revoluciones que aumentan el consumo."},
    {"enunciado": "Si está obligado a respetar las normas sobre tiempos de conducción y descanso, ¿cuál será el tiempo mínimo de descanso semanal?", "opciones": ["38 horas ininterrumpidas.", "45 horas ininterrumpidas.", "22 horas ininterrumpidas."], "respuesta_correcta": 1, "explicacion": "El descanso semanal normal es de al menos 45 horas ininterrumpidas. Puede reducirse a 24 horas como máximo dos veces en un período de cuatro semanas."},
    {"enunciado": "Las anotaciones hechas a mano por el conductor en el disco diagrama del tacógrafo analógico, ¿en qué lugar quedan registradas?", "opciones": ["El conductor no puede anotar a mano ningún dato en el disco.", "En el reverso del disco.", "En el anverso del disco."], "respuesta_correcta": 1, "explicacion": "Las anotaciones manuales (períodos de disponibilidad, trabajo no de conducción, etc.) se registran en el reverso del disco diagrama."},
    {"enunciado": "Si conduce un camión equipado con un eje directriz y otro motriz, ¿en cuál de estos dos ejes van instalados los palieres?", "opciones": ["En el directriz.", "En el motriz.", "Tanto en el eje directriz como en el motriz."], "respuesta_correcta": 1, "explicacion": "Los palieres son los semiejes que transmiten el movimiento desde el diferencial hasta las ruedas; van instalados en el eje motriz."},
    {"enunciado": "¿Qué indicará la emisión de humo negro por el tubo de escape en un motor de combustión?", "opciones": ["Que la combustión es imperfecta debido a un exceso de aire en la mezcla.", "Que el motor consume aceite en exceso.", "Que la combustión es imperfecta porque el filtro de aire está obstruido o porque se inyecta un exceso de carburante."], "respuesta_correcta": 2, "explicacion": "El humo negro indica combustión incompleta por falta de oxígeno (filtro obstruido) o por exceso de combustible inyectado."},
    {"enunciado": "Se denomina tren de carretera al...", "opciones": ["Automóvil constituido por un vehículo de motor acoplado a un semirremolque.", "Automóvil concebido y construido para realizar, principalmente, el arrastre de un remolque o semirremolque.", "Automóvil constituido por un vehículo de motor enganchado a un remolque."], "respuesta_correcta": 2, "explicacion": "El tren de carretera es la combinación de un camión (con carrocería propia) más un remolque enganchado a él, frente al conjunto articulado que usa semirremolque."},
    {"enunciado": "Si debe conducir un camión de más de 3.500 kg de MMA por una vía urbana con tres carriles para el mismo sentido sin marcas longitudinales, ¿por qué carril debe circular?", "opciones": ["Por el carril de la derecha.", "Por el que mejor convenga a su destino.", "Por el carril de la derecha o el central."], "respuesta_correcta": 0, "explicacion": "Los vehículos pesados de más de 3.500 kg de MMA deben circular por el carril de la derecha en vías con múltiples carriles sin señalización."},
    {"enunciado": "¿Qué misión tienen los fusibles en el circuito eléctrico del vehículo?", "opciones": ["Evitar que la corriente que pasa por el circuito eléctrico cambie de sentido.", "Reducir la intensidad de la corriente antes de que pase por los diferentes elementos del circuito.", "Evitar que un aumento de la intensidad de la corriente pueda dañar algún elemento del circuito eléctrico."], "respuesta_correcta": 2, "explicacion": "Los fusibles protegen el circuito eléctrico fundiéndose cuando la intensidad supera el valor máximo permitido, evitando daños en los componentes del sistema."},
    {"enunciado": "Se considera que se obstaculiza gravemente a la circulación con el hecho de efectuar una parada...", "opciones": ["En una zona reservada a carga y descarga.", "Impidiendo la entrada o salida de personas a un inmueble.", "En doble fila."], "respuesta_correcta": 1, "explicacion": "Impedir la entrada o salida de personas a inmuebles (garajes, portales) se considera una obstaculización grave, ya que puede bloquear vehículos de emergencia."},
    {"enunciado": "Si circula con su camión durante la noche y con la vía mojada, ¿cómo afecta esto a la visibilidad?", "opciones": ["Tendrá peor visibilidad.", "Verá mejor a los otros vehículos, ya que se refleja la luz.", "Verá mejor las marcas viales."], "respuesta_correcta": 0, "explicacion": "La vía mojada de noche refleja la luz de los faros de forma difusa, empeorando la visibilidad general del conductor."},
    {"enunciado": "¿Cuál será la función de la válvula de descarga del sistema neumático de frenada?", "opciones": ["Evitar sobrepresiones en el sistema.", "Purgar automáticamente el aire del líquido hidráulico.", "Permitir el paso del aire al circuito del semirremolque."], "respuesta_correcta": 0, "explicacion": "La válvula de descarga evita que la presión del sistema neumático supere los límites de seguridad, protegiéndolo de sobrepresiones."},
    {"enunciado": "¿Cómo deben ir señalizadas, entre la puesta y la salida del sol, las cargas que sobresalgan por la parte trasera del vehículo?", "opciones": ["Únicamente con un panel (V-20).", "Con una luz blanca o, en su defecto, con un dispositivo reflectante blanco.", "Con uno o dos paneles (V-20) y una luz roja."], "respuesta_correcta": 2, "explicacion": "Las cargas traseras sobresalientes deben señalizarse de noche con el panel V-20 y una luz roja, para hacerlas visibles a los conductores que circulen detrás."},
    {"enunciado": "Si conduce un camión de 16.000 kg de MMA, ¿puede circular por el carril de la izquierda en una vía de poblado con tres carriles de circulación para el mismo sentido?", "opciones": ["Sí, siempre que sea el que más convenga a su destino y no constituya un obstáculo.", "Sí, pero sólo cuando vaya a cambiar de dirección a la izquierda.", "No, debo circular por el carril de la derecha."], "respuesta_correcta": 2, "explicacion": "Los camiones con MMA superior a 3.500 kg deben circular obligatoriamente por el carril de la derecha, independientemente del número de carriles disponibles."},
    {"enunciado": "En un motor, además de engrasar las piezas móviles y las paredes del cilindro, ¿qué otra utilidad tiene el aceite?", "opciones": ["No tiene más utilidad.", "Refrigerar y evitar la excesiva dilatación de las piezas.", "Aumentar la potencia del motor."], "respuesta_correcta": 1, "explicacion": "El aceite del motor también actúa como refrigerante secundario, absorbiendo el calor de las piezas y reduciéndolo a través del circuito de lubricación."},
    {"enunciado": "Tanto la carga como los accesorios utilizados para su acondicionamiento o protección deberán estar dispuestos de forma que...", "opciones": ["No puedan ocultar los dispositivos de alumbrado, señalización luminosa, placas de matrícula ni advertencias manuales de los conductores.", "No puedan ocultar los dispositivos de alumbrado o de señalización luminosa y las advertencias manuales de los conductores.", "No puedan ocultar las placas de matrícula u otras placas o distintivos obligatorios y las advertencias manuales de los conductores."], "respuesta_correcta": 0, "explicacion": "La carga no debe tapar ni las luces, ni las señales luminosas, ni las matrículas, ni ningún distintivo obligatorio, ni impedir las señales manuales del conductor."},
    {"enunciado": "¿Puede comprobarse si una luna es laminada o templada por el comportamiento en su rotura?", "opciones": ["No se puede comprobar, ya que cuando se rompen las dos se comportan igual.", "Sí; la laminada no pierde visibilidad porque los fragmentos quedan unidos por la lámina intermedia.", "Sí; la templada no pierde visibilidad al saltar los cortes desde el golpe hacia el exterior."], "respuesta_correcta": 1, "explicacion": "La luna laminada, al romperse, mantiene los fragmentos unidos por la lámina de PVB, conservando la visibilidad. La templada se fragmenta en pequeños trozos."},
    {"enunciado": "La velocidad de diseño de una vía es...", "opciones": ["Lo más despacio que podemos circular con seguridad.", "Una velocidad inadecuada.", "La velocidad máxima segura en condiciones favorables según el trazado de la vía."], "respuesta_correcta": 2, "explicacion": "La velocidad de diseño es la máxima velocidad a la que se puede circular con seguridad en condiciones favorables, según las características geométricas de la vía."},
    {"enunciado": "¿Qué es necesario hacer cuando se transporte una carga indivisible que sobresalga de la proyección en planta del vehículo?", "opciones": ["Cubrir la carga para reducir los efectos de los posibles choques o roces.", "Es suficiente con señalizar la carga correctamente.", "Solicitar una autorización especial, en cualquier caso."], "respuesta_correcta": 0, "explicacion": "Las cargas indivisibles que sobresalen lateralmente deben cubrirse con protecciones para evitar daños a otros vehículos o peatones en caso de contacto."},
    {"enunciado": "¿Dónde va situado el termostato en el sistema de refrigeración del motor?", "opciones": ["En el interior de la culata, ya que es la pieza que alcanza mayor temperatura.", "En la canalización de salida del líquido refrigerante que va desde el motor hacia la parte superior del radiador.", "En la parte baja del radiador, para medir la temperatura del líquido refrigerante."], "respuesta_correcta": 1, "explicacion": "El termostato se sitúa a la salida del motor (antes del radiador) para regular el paso del líquido refrigerante según la temperatura del motor."},

    # ── practicatest preguntas frecuentes ───────────────────────────────────
    {"enunciado": "Se permitirá el adelantamiento por la derecha, salvo...", "opciones": ["Cuando existan dos carriles para el mismo sentido y no estén delimitados por marcas viales.", "A los vehículos que vayan a girar a la izquierda.", "A los tranvías que circulen por el centro de la calzada."], "respuesta_correcta": 1, "explicacion": "Está prohibido adelantar por la derecha a vehículos que vayan a girar a la izquierda, ya que el adelantamiento por ese lado aumenta el riesgo de colisión."},
    {"enunciado": "La velocidad máxima, con carácter general, para un vehículo especial cuando circula por vías de uso público es de...", "opciones": ["40 kilómetros por hora.", "25 kilómetros por hora.", "45 kilómetros por hora."], "respuesta_correcta": 0, "explicacion": "La velocidad máxima general para vehículos especiales en vías de uso público es de 40 km/h, salvo que la señalización indique otra."},
    {"enunciado": "En condiciones ambientales adversas, la separación o distancia de seguridad debe aumentarse en al menos...", "opciones": ["Un segundo más.", "Dos segundos más.", "Cinco segundos más."], "respuesta_correcta": 1, "explicacion": "En condiciones adversas (niebla, lluvia, hielo) la distancia de seguridad debe incrementarse al menos dos segundos adicionales sobre la distancia de seguridad normal."},
    {"enunciado": "En una situación incierta, podrá ganar unos metros vitales para evitar un accidente si coloca el pie...", "opciones": ["Encima del pedal del freno, presionándolo levemente.", "Frente al pedal del embrague.", "Frente al pedal del freno sin llegar a presionar."], "respuesta_correcta": 2, "explicacion": "Tener el pie frente al freno sin presionar permite reducir el tiempo de reacción ante un peligro, ganando metros cruciales para evitar un accidente."},
    {"enunciado": "¿Qué es lo primero que toda persona debe tener en cuenta ante un accidente de tráfico?", "opciones": ["Proteger el lugar del accidente.", "Protegerse a sí misma.", "Proteger a las víctimas."], "respuesta_correcta": 1, "explicacion": "La regla básica ante un accidente es PAS: Protegerse a uno mismo primero, luego Avisar a los servicios de emergencia y después Socorrer a las víctimas."},
]

# Cargar existentes
with open(RUTA, encoding="utf-8") as f:
    existentes = json.load(f)

# Normalizar texto para comparación
def norm(s):
    return re.sub(r'\s+', ' ', s.strip().lower())[:80]

existentes_norm = {norm(p["enunciado"]) for p in existentes}

# Filtrar duplicados
next_id = max(p["id"] for p in existentes) + 1
añadidas = 0
for q in nuevas:
    clave = norm(q["enunciado"])
    if clave in existentes_norm:
        print(f"DUPLICADO: {q['enunciado'][:60]}")
        continue
    q["id"] = next_id
    existentes.append(q)
    existentes_norm.add(clave)
    next_id += 1
    añadidas += 1

print(f"\nPreguntas añadidas: {añadidas}")
print(f"Total preguntas C: {len(existentes)}")

with open(RUTA, "w", encoding="utf-8", newline="\n") as f:
    json.dump(existentes, f, ensure_ascii=False, indent=4)

print("Guardado OK")
